### ISSUE TITLE
请教下RX580独显的问题

### ISSUE THREAD

**Issue by stareko** [nagaame/MSI-B460M-MORTAR-WIFI-10700-HACKINTOSH#1]
首先感谢分享~！
请问我配置基本一样除了独显是RX580,我该套用哪个config.plist文件？
另外我的独显是否可以HDMI输出？
感谢~

**Comment by nagaame** [comment]
`config.550.plist` 这个配置文件, 独显可以使用HDMI或者DP都是没有问题的

**Comment by nagaame** [comment]
> 首先感谢分享~！ 请问我配置基本一样除了独显是RX580,我该套用哪个config.plist文件？ 另外我的独显是否可以HDMI输出？ 感谢~

`config.550.plist` 这个配置文件, 独显可以使用HDMI或者DP都是没有问题的
