### ISSUE TITLE
关于唤醒问题

### ISSUE THREAD

**Issue by EvanLin1003** [nagaame/MSI-B460M-MORTAR-WIFI-10700-HACKINTOSH#3]
大佬 我使用你的EFI  我的是不带WIFI的迫击炮 （MIS-B460M-MORTAR+10500+BCM943602CD）  现在唤醒有问题， 睡一会正常  睡久了就死机了  请教一下是什么问题

**Comment by nagaame** [comment]
可以看[这里](https://github.com/nagaame/MSI-B460M-MORTAR-WIFI-10700-HACKINTOSH#usb%E5%AE%9A%E5%88%B6), 应该是你的USB还没有定制，可以在配置里边勾选这两个定制好的驱动或者自己定制一下USB就不会有唤醒问题了

**Comment by EvanLin1003** [comment]
我看唤醒报错日志 说是网卡的问题  按照你说的方法可以解决？
![560241ce5435657e9a06a192228d430](https://user-images.githubusercontent.com/34332393/199920367-a422af45-302e-4a02-9ef7-0ba77d2b7a94.jpg)

**Comment by nagaame** [comment]
如果你的无线网卡的蓝牙使用了USB插口，也就是蓝牙走USB协议的话，可以用这个方式解决

**Comment by nagaame** [comment]
把无线网卡的蓝牙使用的USB的主板插口对应的逻辑接口，一般是USB2协议，使用工具定制成**内建**就可以了

**Comment by EvanLin1003** [comment]
OK 我操作下 不行再来请教

**Comment by EvanLin1003** [comment]
大佬 我定制了usb  睡久了还睡死掉了。现在看日志说（DarkWake from Normal Sleep [CDNP] : due to GLAN XDCI/ Using AC (Charge:0%) 46 secs   ） 大概意思就说正常唤醒。 什么情况。指导一下

**Comment by EvanLin1003** [comment]
我看了我网卡走的pcie。蓝牙走的事usb 这个有什么问题不

**Comment by nagaame** [comment]
没有什么问题，你的这个网卡蓝牙就是走的usb，你确定你的蓝牙走的USB已经内建成功了吗

**Comment by nagaame** [comment]
具体教程可以参考[这里](https://apple.sqlsec.com/6-%E5%AE%9E%E7%94%A8%E5%A7%BF%E5%8A%BF/6-1.html)

**Comment by EvanLin1003** [comment]
我定制了后面两个USB3.0(用于鼠标和键盘)，前面一个USB3.0 然后蓝牙用的是里面的USB2.0  网卡用的PCIE  其他全部删除了   我回去再试下吧

**Comment by EvanLin1003** [comment]
我按照教程做了一遍  结果还是一样睡久了就死掉了

**Comment by nagaame** [comment]
<img width="1132" alt="2022-11-08_23-45-29" src="https://user-images.githubusercontent.com/6214936/200610882-87b84aca-2542-4a14-aaf4-708e312e6a09.png">
<img width="803" alt="2022-11-08_23-46-48" src="https://user-images.githubusercontent.com/6214936/200610900-fdc5e7a5-2f5d-4d96-9251-b32729be9b6a.png">
检查一下这两个地方, 确保蓝牙USB端口内建成功, 如果内建不成功可能是休眠唤醒, 内建成功但是休眠睡死了可能是其他问题
